/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedLicensesRouteImport } from './routes/_authenticated/licenses'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated/maintenance'
import { Route as AuthenticatedPeopleDepartmentsRouteImport } from './routes/_authenticated/people-departments'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedAssetsIndexRouteImport } from './routes/_authenticated/assets.index'
import { Route as AuthenticatedAssetsIdRouteImport } from './routes/_authenticated/assets.$id'
import { Route as AuthenticatedLicensesIdRouteImport } from './routes/_authenticated/licenses.$id'
import { Route as AuthenticatedPeopleDepartmentsIdRouteImport } from './routes/_authenticated/people-departments.$id'
import { Route as AuthenticatedPeopleDepartmentsEmployeeIdRouteImport } from './routes/_authenticated/people-departments.employee.$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLicensesRoute = AuthenticatedLicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeopleDepartmentsRoute =
  AuthenticatedPeopleDepartmentsRouteImport.update({
    id: '/people-departments',
    path: '/people-departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssetsIndexRoute =
  AuthenticatedAssetsIndexRouteImport.update({
    id: '/assets/',
    path: '/assets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssetsIdRoute = AuthenticatedAssetsIdRouteImport.update({
  id: '/assets/$id',
  path: '/assets/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLicensesIdRoute = AuthenticatedLicensesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedLicensesRoute,
} as any)
const AuthenticatedPeopleDepartmentsIdRoute =
  AuthenticatedPeopleDepartmentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPeopleDepartmentsRoute,
  } as any)
const AuthenticatedPeopleDepartmentsEmployeeIdRoute =
  AuthenticatedPeopleDepartmentsEmployeeIdRouteImport.update({
    id: '/employee/$id',
    path: '/employee/$id',
    getParentRoute: () => AuthenticatedPeopleDepartmentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/licenses': typeof AuthenticatedLicensesRouteWithChildren
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/people-departments': typeof AuthenticatedPeopleDepartmentsRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/assets/$id': typeof AuthenticatedAssetsIdRoute
  '/licenses/$id': typeof AuthenticatedLicensesIdRoute
  '/people-departments/$id': typeof AuthenticatedPeopleDepartmentsIdRoute
  '/assets/': typeof AuthenticatedAssetsIndexRoute
  '/people-departments/employee/$id': typeof AuthenticatedPeopleDepartmentsEmployeeIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/licenses': typeof AuthenticatedLicensesRouteWithChildren
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/people-departments': typeof AuthenticatedPeopleDepartmentsRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/assets/$id': typeof AuthenticatedAssetsIdRoute
  '/licenses/$id': typeof AuthenticatedLicensesIdRoute
  '/people-departments/$id': typeof AuthenticatedPeopleDepartmentsIdRoute
  '/assets': typeof AuthenticatedAssetsIndexRoute
  '/people-departments/employee/$id': typeof AuthenticatedPeopleDepartmentsEmployeeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/licenses': typeof AuthenticatedLicensesRouteWithChildren
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRoute
  '/_authenticated/people-departments': typeof AuthenticatedPeopleDepartmentsRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/assets/$id': typeof AuthenticatedAssetsIdRoute
  '/_authenticated/licenses/$id': typeof AuthenticatedLicensesIdRoute
  '/_authenticated/people-departments/$id': typeof AuthenticatedPeopleDepartmentsIdRoute
  '/_authenticated/assets/': typeof AuthenticatedAssetsIndexRoute
  '/_authenticated/people-departments/employee/$id': typeof AuthenticatedPeopleDepartmentsEmployeeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/inventory'
    | '/licenses'
    | '/maintenance'
    | '/people-departments'
    | '/reports'
    | '/settings'
    | '/assets/$id'
    | '/licenses/$id'
    | '/people-departments/$id'
    | '/assets/'
    | '/people-departments/employee/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/inventory'
    | '/licenses'
    | '/maintenance'
    | '/people-departments'
    | '/reports'
    | '/settings'
    | '/'
    | '/assets/$id'
    | '/licenses/$id'
    | '/people-departments/$id'
    | '/assets'
    | '/people-departments/employee/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/inventory'
    | '/_authenticated/licenses'
    | '/_authenticated/maintenance'
    | '/_authenticated/people-departments'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/assets/$id'
    | '/_authenticated/licenses/$id'
    | '/_authenticated/people-departments/$id'
    | '/_authenticated/assets/'
    | '/_authenticated/people-departments/employee/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/licenses': {
      id: '/_authenticated/licenses'
      path: '/licenses'
      fullPath: '/licenses'
      preLoaderRoute: typeof AuthenticatedLicensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people-departments': {
      id: '/_authenticated/people-departments'
      path: '/people-departments'
      fullPath: '/people-departments'
      preLoaderRoute: typeof AuthenticatedPeopleDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets/': {
      id: '/_authenticated/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AuthenticatedAssetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets/$id': {
      id: '/_authenticated/assets/$id'
      path: '/assets/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AuthenticatedAssetsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/licenses/$id': {
      id: '/_authenticated/licenses/$id'
      path: '/$id'
      fullPath: '/licenses/$id'
      preLoaderRoute: typeof AuthenticatedLicensesIdRouteImport
      parentRoute: typeof AuthenticatedLicensesRoute
    }
    '/_authenticated/people-departments/$id': {
      id: '/_authenticated/people-departments/$id'
      path: '/$id'
      fullPath: '/people-departments/$id'
      preLoaderRoute: typeof AuthenticatedPeopleDepartmentsIdRouteImport
      parentRoute: typeof AuthenticatedPeopleDepartmentsRoute
    }
    '/_authenticated/people-departments/employee/$id': {
      id: '/_authenticated/people-departments/employee/$id'
      path: '/employee/$id'
      fullPath: '/people-departments/employee/$id'
      preLoaderRoute: typeof AuthenticatedPeopleDepartmentsEmployeeIdRouteImport
      parentRoute: typeof AuthenticatedPeopleDepartmentsRoute
    }
  }
}

interface AuthenticatedLicensesRouteChildren {
  AuthenticatedLicensesIdRoute: typeof AuthenticatedLicensesIdRoute
}

const AuthenticatedLicensesRouteChildren: AuthenticatedLicensesRouteChildren = {
  AuthenticatedLicensesIdRoute: AuthenticatedLicensesIdRoute,
}

const AuthenticatedLicensesRouteWithChildren =
  AuthenticatedLicensesRoute._addFileChildren(
    AuthenticatedLicensesRouteChildren,
  )

interface AuthenticatedPeopleDepartmentsRouteChildren {
  AuthenticatedPeopleDepartmentsIdRoute: typeof AuthenticatedPeopleDepartmentsIdRoute
  AuthenticatedPeopleDepartmentsEmployeeIdRoute: typeof AuthenticatedPeopleDepartmentsEmployeeIdRoute
}

const AuthenticatedPeopleDepartmentsRouteChildren: AuthenticatedPeopleDepartmentsRouteChildren =
  {
    AuthenticatedPeopleDepartmentsIdRoute:
      AuthenticatedPeopleDepartmentsIdRoute,
    AuthenticatedPeopleDepartmentsEmployeeIdRoute:
      AuthenticatedPeopleDepartmentsEmployeeIdRoute,
  }

const AuthenticatedPeopleDepartmentsRouteWithChildren =
  AuthenticatedPeopleDepartmentsRoute._addFileChildren(
    AuthenticatedPeopleDepartmentsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedLicensesRoute: typeof AuthenticatedLicensesRouteWithChildren
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRoute
  AuthenticatedPeopleDepartmentsRoute: typeof AuthenticatedPeopleDepartmentsRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAssetsIdRoute: typeof AuthenticatedAssetsIdRoute
  AuthenticatedAssetsIndexRoute: typeof AuthenticatedAssetsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedLicensesRoute: AuthenticatedLicensesRouteWithChildren,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedPeopleDepartmentsRoute:
    AuthenticatedPeopleDepartmentsRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAssetsIdRoute: AuthenticatedAssetsIdRoute,
  AuthenticatedAssetsIndexRoute: AuthenticatedAssetsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
