/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedTonersRouteImport } from './routes/_authenticated/toners'
import { Route as AuthenticatedPrintersIndexRouteImport } from './routes/_authenticated/printers.index'
import { Route as AuthenticatedPrintersIdRouteImport } from './routes/_authenticated/printers.$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTonersRoute = AuthenticatedTonersRouteImport.update({
  id: '/toners',
  path: '/toners',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrintersIndexRoute =
  AuthenticatedPrintersIndexRouteImport.update({
    id: '/printers/',
    path: '/printers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrintersIdRoute = AuthenticatedPrintersIdRouteImport.update({
  id: '/printers/$id',
  path: '/printers/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/toners': typeof AuthenticatedTonersRoute
  '/printers/$id': typeof AuthenticatedPrintersIdRoute
  '/printers/': typeof AuthenticatedPrintersIndexRoute
}
export interface FileRoutesByTo {
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/toners': typeof AuthenticatedTonersRoute
  '/': typeof AuthenticatedIndexRoute
  '/printers/$id': typeof AuthenticatedPrintersIdRoute
  '/printers': typeof AuthenticatedPrintersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/toners': typeof AuthenticatedTonersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/printers/$id': typeof AuthenticatedPrintersIdRoute
  '/_authenticated/printers/': typeof AuthenticatedPrintersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reports'
    | '/settings'
    | '/suppliers'
    | '/toners'
    | '/printers/$id'
    | '/printers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/reports'
    | '/settings'
    | '/suppliers'
    | '/toners'
    | '/'
    | '/printers/$id'
    | '/printers'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/suppliers'
    | '/_authenticated/toners'
    | '/_authenticated/'
    | '/_authenticated/printers/$id'
    | '/_authenticated/printers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/toners': {
      id: '/_authenticated/toners'
      path: '/toners'
      fullPath: '/toners'
      preLoaderRoute: typeof AuthenticatedTonersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/printers/': {
      id: '/_authenticated/printers/'
      path: '/printers'
      fullPath: '/printers/'
      preLoaderRoute: typeof AuthenticatedPrintersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/printers/$id': {
      id: '/_authenticated/printers/$id'
      path: '/printers/$id'
      fullPath: '/printers/$id'
      preLoaderRoute: typeof AuthenticatedPrintersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedTonersRoute: typeof AuthenticatedTonersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPrintersIdRoute: typeof AuthenticatedPrintersIdRoute
  AuthenticatedPrintersIndexRoute: typeof AuthenticatedPrintersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedTonersRoute: AuthenticatedTonersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPrintersIdRoute: AuthenticatedPrintersIdRoute,
  AuthenticatedPrintersIndexRoute: AuthenticatedPrintersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
